export const CATEGORIES = { // product categories keywords from backend
    AutomotiveChemicalsAndOils: 'AutomotiveChemicalsAndOils',
    TransmissionOils : 'TransmissionOils',
    AutomotiveLubricants : 'AutomotiveLubricants',
    AutomotiveChemicals : 'AutomotiveChemicals',
    AutomotiveOils : 'Automotive Oils',
    HydraulicOils : 'HydraulicOils',
    ChainOils : 'ChainOils',
    FlushingOils : 'FlushingOils',
    IndustrialOils : 'IndustrialOils',
    UniversalOils : 'UniversalOils',
    WindshieldWasherFluids : 'WindshieldWasherFluids',
    Coolants : 'Coolants',
    AutoAdditives : 'AutoAdditives',
    CarCleaners : 'CarCleaners',
    AutomotiveSealants : 'AutomotiveSealants',
    CarPaints : 'CarPaints',
    BrakeFluids : 'BrakeFluids',
    SolventsForCarPaint : 'SolventsForCarPaint',
    MotorOils: 'MotorOils',     
}