export const controlsConstants = {
    OPEN_CART: 'OPEN_CART',
    CLOSE_CART: 'CLOSE_CART',
    OPEN_EXIT_DIALOG: 'OPEN EXIT DIALOG',
    CLOSE_EXIT_DIALOG: 'CLOSE EXIT DIALOG',
    SHOW_LOADER: 'SHOW LOADER',
    HIDE_LOADER: 'HIDE LOADER'
}