version: '3.4'

services:
  market-front:
    image: 038641204801.dkr.ecr.eu-west-2.amazonaws.com/market-prod:market-front
    env_file:
      - ./.env.prod
    build:
      context: .
      dockerfile: ./DockerfileFront.prod
    expose:
      - 3000
    ports:
      - 3000:3000
  market:
    image: 038641204801.dkr.ecr.eu-west-2.amazonaws.com/market-prod:market-server
    env_file:
      - ./.env.prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
  nginx-proxy:
    image: 038641204801.dkr.ecr.eu-west-2.amazonaws.com/market-prod:nginx-proxy
    env_file:
      - ./.env.prod
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - market
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes: 
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal  --email yuriyzagorulko602@gmail.com -d v16.com.ua -d www.v16.com.ua --agree-tos # --dry-run (for test)
  #   depends_on:
  #     - nginx-proxy
volumes:
  static_volume:
  media_volume:
    