version: '3.4'

services:
  market:
    image: 038641204801.dkr.ecr.eu-west-2.amazonaws.com/market-prod:market-server
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
  nginx-proxy:
    image: 038641204801.dkr.ecr.eu-west-2.amazonaws.com/market-prod:nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - market
  nginx-proxy-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
    