# Generated by Django 3.2 on 2021-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='discountPrice',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='minAmount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='productCode',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='This is the description of the product', max_length=2000),
        ),
    ]
