# Generated by Django 3.2.9 on 2021-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20211227_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCode',
        ),
        migrations.AddField(
            model_name='product',
            name='vinCode',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
