# Generated by Django 3.2.9 on 2021-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20211227_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
