# Generated by Django 4.0.1 on 2022-06-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='market.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(default='', max_length=300),
        ),
    ]
