# Generated by Django 4.0.1 on 2022-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='keyWord',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
