# Generated by Django 4.0.1 on 2022-08-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_productcategory_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='market.imagealbum'),
        ),
    ]
