# Generated by Django 4.0.1 on 2022-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_product_characteristics_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
