# Generated by Django 4.2.7 on 2023-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_order_internalnotes_order_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendorCodeAVDTrade',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('JUSTIN', 'Justin'), ('NEW_POST', 'Newpost'), ('NEW_POST_COURIER', 'Newpostcourier')], max_length=100),
        ),
    ]
