# Generated by Django 4.2.7 on 2024-01-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='isRootCategory',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
