# Generated by Django 4.2.7 on 2024-01-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_UA',
            field=models.CharField(default='', max_length=300),
        ),
    ]
