# Generated by Django 4.2.7 on 2024-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_productcategory_name_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='default-image.jpeg', upload_to='images/'),
        ),
    ]
