# Generated by Django 4.2.7 on 2025-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='market.productcategory'),
        ),
    ]
