# Generated by Django 4.2.7 on 2025-08-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='market.productcategory'),
        ),
    ]
